num1=int(input("Please Enter the first Integer: "))
num2=int(input("Please Enter the second Integer: "))
print(f"The sum of {num1} and {num2} is: {num1+num2}")
print(f"The difference of {num1} and {num2} is: {num1-num2}")
print(f"The product of {num1} and {num2} is: {num1*num2}")
print(f"The qoutient of {num1} and {num2} is: {int(num1/num2)} with remainder: {num1%num2}")